language: python
python:
  - "2.7"
  - "3.2"
#  - "nightly"

sudo: false

addons:
  apt:
    packages:
      - python-scipy

virtualenv:
  system_site_packages: true

# command to install dependencies
install:
  - "pip install ."
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install nose"
  - "pip install -r requirements.txt"

# command to run tests
script:
  - cd $HOME/build/atmos-python/atmos/atmos/tests
  - python run_tests.py
after_success:  
  - coveralls
